{"name": "Проверка получения ошибки при повторном создании уже существующего пользователя", "status": "passed", "description": "Невалидный запрос на создание пользователя, который уже существует в системе, ожидаем ошибку клиента (403) и текста ответа 'User already exists'", "steps": [{"name": "Проверка статуса ответа", "status": "passed", "parameters": [{"name": "response", "value": "<Response [403]>"}, {"name": "code", "value": "403"}], "start": 1704576576538, "stop": 1704576576538}, {"name": "Проверка ответа 'message'", "status": "passed", "parameters": [{"name": "response", "value": "<Response [403]>"}, {"name": "key", "value": "'message'"}, {"name": "text", "value": "'User already exists'"}], "start": 1704576576539, "stop": 1704576576539}], "start": 1704576575917, "stop": 1704576576541, "uuid": "a8846fde-b6bd-406b-8060-340ea122e266", "historyId": "f35bc668beaf3ad365429c03cd112338", "testCaseId": "f35bc668beaf3ad365429c03cd112338", "fullName": "tests.test_create_user.TestCreateUser#test_create_user_user_already_exists_error", "labels": [{"name": "feature", "value": "Проверка ручки создания пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_user"}, {"name": "subSuite", "value": "TestCreateUser"}, {"name": "host", "value": "DESKTOP-RUURDMU"}, {"name": "thread", "value": "6308-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_user"}]}